### ISSUE TITLE
is this malware

### ISSUE THREAD

**Issue by W1lcro** [AsjadOooO/Zero-attacker#22]

**Comment by IronDemiGod** [comment]
bruh

**Comment by ZackeryRSmith** [comment]
@W1lcro to be quite frank. No. This is not malware. How can I tell, well the code is open to public view. If you are really that concerned that this is malware you can build the project _yourself_ instead of downloading the pre-compiled binary in the [releases](https://github.com/AsjadOooO/Zero-attacker/releases/).

**Comment by logicguy1** [comment]
Its not tho, lol. I Think you misunderstand something about what open source means
